Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "forwarded_port", guest:80, host:100, auto_correct: true
    config.vm.synced_folder ".", "/var/www/html"  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"  
  end
  config.vm.provision "shell", inline: <<-SHELL
    # Packages vom lokalen Server holen
    # sudo sed -i -e"1i deb {{config.server}}/apt-mirror/mirror/archive.ubuntu.com/ubuntu xenial main restricted" /etc/apt/sources.list 
    sudo apt-get install apache2
    sudo apt-get install libapache2-mod-proxy-html
    sudo apt-get install libxml2-dev

    sudo systemctl restart apache2

    sudo a2enmod proxy 
    sudo a2enmod proxy_html
    sudo a2enmod proxy_http
    sudo systemctl restart apache2

    sudo echo ServerName localhost >> /etc/apache2/apache2.conf
  SHELL
  end